name: tic_tac_toe_real_game
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # State Managemen  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Remote API
  dio: ^5.3.3
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.3.1
  # Value equality
  equatable: ^2.0.5
  # Service locator 
  get_it: ^7.6.4
  # A flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  # Functional programming things
  dartz: ^0.10.1
  # An SVG rendering and widget library for Flutter
  flutter_svg: ^2.0.7
  # Reading and writing simple key-value pairs
  shared_preferences: ^2.2.2
  # Easy and Fast internationalizing and localization
  flutter_localizations:
    sdk: flutter  
  # Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # Change between light and dark theme.
  adaptive_theme: ^3.4.1
  # Connectivity
  internet_connection_checker: ^1.0.0+1
  # Handle offline / online connectivity.
  flutter_offline: ^3.0.0
  # Onboarding screens
  introduction_screen: ^3.1.12
  # Page Transition.
  page_transition: ^2.1.0 
  # Google sign in
  google_sign_in: ^6.1.5
  # Easily add Facebook login feature in your application. User profile information included.
  flutter_login_facebook: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/gif/
    - assets/images/json/
    - assets/images/jpg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
